### ISSUE TITLE
Windows OS - product download failed Directory name is invalid

### ISSUE THREAD

**Issue by KyleMartin901** [pivotal-cf/pivnet-cli#26]
I am trying to download a product file using the cli on Windows 10 and get the error `<failed to get disk free space: The directory name is invalid>`.

```powershell
$ .\pivnet.exe download-product-files -p pcf-app-autoscaler -r 2.0.40 -i 125013 -d C:\Temp --accept-eula

2018/08/14 11:33:32 Downloading 'autoscaler-for-pcf-cliplugin-windows64-exe-2.0.40' to 'C:\Temp\autoscaler-for-pcf-cliplugin-windows64-exe-2.0.40'
failed to get disk free space: The directory name is invalid.
```

```powershell
$ .\pivnet.exe --version
0.0.52
```

**Comment by pnikonowicz** [comment]
Sorry for your trouble. It appears there is a problem with the library we are using which checks OS disk space. We have scheduled this bug to be fixed in our internal tracking system. 

As a workaround, we recommend using this version to download product files in windows:
https://github.com/pivotal-cf/pivnet-cli/releases/download/v0.0.49/pivnet-windows-amd64-0.0.49

Let us know if there are any problems with this for you.

**Comment by xtreme-debbie-chen** [comment]
Fixed in https://github.com/pivotal-cf/pivnet-cli/releases/tag/v0.0.53
