### ISSUE TITLE
Downloads not working with the latest cli

### ISSUE THREAD

**Issue by rahulkj** [pivotal-cf/pivnet-cli#3]
Hi,

I've been trying to build my own concourse pipleline using this cli.. and when I run the following command, the command exists and no file is downloaded. Am I missing something?

`pivnet-cli download-product-files -p stemcells -r 3263.12 -i 3243 -d . --verbose`

**Comment by robdimsdale** [comment]
@rahulkj I think the issue here is that `-i 3243` is not a valid ID for the stemcells product here - I think the UI could do a better job telling you that nothing can be downloaded.

If you want to work with `-i` you should use one of the following IDs:

```
pivnet pfs -p stemcells -r 3263.12 --format json | jq .[].id
10197
10195
10194
10193
10192
10191
```

Alternatively, using `-g '*some-glob*'` might be more intuitive when locating a stemcell for a particular IAAS.

I've created [pivnet CLI should error when no files match provided IDs or globs](https://www.pivotaltracker.com/story/show/135824667) to make it more obvious what's going on.

Let me know if you have further questions.

**Comment by rahulkj** [comment]
That was it!! Thank you and an error message will be much appreciated

**Comment by robdimsdale** [comment]
Great, thanks. I'll close this now - the improved error message story is prioritized.
